# Changes here will be overwritten by Copier
_commit: f8b65ae
_src_path: https://github.com/lenskit/lk-project-template
owner: Drexel University and contributors
package_name: binpickle
project_descr: Optimized format for pickling binary data.
project_name: binpickle
project_title: BinPickle
require_lint: true
start_year: 2020
typecheck: true
