# Dev environment
name: binpickle
channels:
- conda-forge
- defaults
deps:
- python
- flit>=2
- msgpack-python
- python-blosc
- numpy>=1.17
- pandas>=1.0
- pytest
- pytest-cov
- hypothesis
- sphinx
- flake8
- rstcheck
