# Dev environment
name: binpickle
channels:
- conda-forge
# - defaults
dependencies:
- python=3.8
- pip
- msgpack-python
- python-blosc
- numcodecs
- numpy>=1.17
- pandas>=1.0
- pytest
- pytest-cov
- hypothesis
- sphinx
- flake8
- twine
- pip:
    - rstcheck
