{% set data = load_setup_py_data() %}
{% set version = '0.1' %}
package:
  name: binpickle
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') > '0' %}
  version: {{version}}.dev{{GIT_DESCRIBE_NUMBER}}+{{GIT_DESCRIBE_HASH}}
  {% else %}
  version: {{version}}
  {% endif %}

about:
  home: https://binpickle.lenskit.org
  license: MIT
  license_file: LICENSE
  summary: efficient binary storage of ML models

source:
  path: ../

build:
  script: python -m pip install --no-deps .

requirements:
  host:
    - python {{ python }}
    - pip
    - flit-core
  run:
    - python
    - python-blosc
    - msgpack-python
    - pickle5 #[py<38]

test:
  source_files:
    - tests
    - tests/*.py
  requires:
    - pytest
    - hypothesis
    - pandas>=1.0
    - numpy>=1.17
  commands:
    - python -m pytest tests
