from abc import ABC
from typing import Optional, Self
from typing_extensions import Buffer

class Codec(ABC):
    codec_id: Optional[str]

    def encode(self, buf: Buffer) -> Buffer: ...
    def decode(self, buf: Buffer, out: Optional[Buffer] = None) -> Buffer: ...
    def get_config(self) -> dict: ...
    @classmethod
    def from_config(cls, cfg: dict) -> Self: ...
