name: Package for Conda
on:
  push:
    branches:
      - master
    tag:
jobs:
  conda:
    name: Build Packages on ${{matrix.platform}}
    runs-on: ${{matrix.image}}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        include:
        - platform: macos
          condaplat: osx-64
          image: macos-latest
        - platform: ubuntu
          condaplat: linux-64
          image: ubuntu-latest
        - platform: windows
          condaplat: osx-64
          image: windows-2016

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Fix Conda Perms
      if: runner.os == 'macOS'
      run: sudo chown -R $USER $CONDA/

    - name: Set Conda path
      run: echo "::add-path::$CONDA/condabin"
      shell: bash

    - name: Install Conda deps
      run: |
        conda update -qy --all
        conda install -qy conda-build

    - name: Build Conda packages
      run: conda build -c conda-forge conda

    - name: Copy Conda packages
      run: |
        mkdir dist
        cp -r $CONDA/conda-bld/${{matrix.condaplat}}/ dist
        ls -lR dist
      shell: bash

    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: conda-pkgs
        path: dist
