name: Test and Package
on:
  push:
    branches:
      - master
  release:
    types: [created,published]
  pull_request:

jobs:
  lint:
    name: Check Source Style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install environment
      run: |
        pip install -U setuptools wheel

    - name: Prep Pip caching
      id: pip-cache
      run: |
        python setup.py egg_info
        echo "::set-output name=dir::$(pip cache dir)"
      shell: bash

    - name: Cache Pip wheels
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: py38-lint-pip-${{ hashFiles('*.egg-info/requires.txt')}}

    - name: Install package
      run: |
        pip install -e '.[dev]'

    - name: Run lint
      run: |
        # Flake8 problem matcher & transform regex from https://github.com/TrueBrain/actions-flake8
        echo "::add-matcher::.github/flake8-matcher.json"
        set -o pipefail
        flake8 |sed -r 's/: ([^W][0-9][0-9][0-9])/: error: \1/;s/: (W[0-9][0-9][0-9])/: warning: \1/'
        echo "::remove-matcher owner=flake8::"

  test:
    name: Test with Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        python:
        - 3.6
        - 3.7
        - 3.8

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}

    - name: Install environment
      run: |
        pip install -U setuptools wheel

    - name: Prep Pip cache
      id: pip-cache
      run: |
        python setup.py egg_info
        echo "::set-output name=dir::$(pip cache dir)"
      shell: bash

    - name: Cache Pip wheels
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ matrix.platform }}-py${{ matrix.python }}-pip-${{ hashFiles('*.egg-info/requires.txt')}}

    - name: Install package
      run: |
        pip install -e '.[dev,test,blosc,numcodecs]'

    - name: Run tests
      run: python -m pytest --cov=binpickle --cov-report=xml tests

    - name: Upload coverage
      uses: codecov/codecov-action@v1

  no-extras:
    name: Test without extras
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install environment
      run: |
        pip install -U setuptools wheel

    - name: Get Pip cache dir
      id: pip-cache
      run: |
        python setup.py egg_info
        echo "::set-output name=dir::$(pip cache dir)"
      shell: bash

    - name: Cache Pip wheels
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: no-extras-pip-${{ hashFiles('*.egg-info/requires.txt')}}

    - name: Install package
      run: |
        pip install -e '.[dev,test]'

    - name: Run tests
      run: python -m pytest --cov=binpickle --cov-report=xml tests

    - name: Upload coverage
      uses: codecov/codecov-action@v1

  sdist:
    name: Build Source Packages
    runs-on: ubuntu-latest
    needs: [test, lint, no-extras]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python deps
      run: pip install -U pip setuptools wheel

    - name: Build source dist
      run: python setup.py sdist

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Save archive
      uses: actions/upload-artifact@v1
      with:
        name: pypi-pkgs
        path: dist

  conda:
    name: Build Conda Packages on ${{matrix.platform}}
    runs-on: ${{matrix.image}}
    needs: sdist
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        include:
        - platform: macos
          condaplat: osx-64
          image: macos-latest
        - platform: ubuntu
          condaplat: linux-64
          image: ubuntu-latest
        - platform: windows
          condaplat: win-64
          image: windows-2016

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Fix Conda Perms
      if: runner.os == 'macOS'
      run: sudo chown -R $USER $CONDA/

    - name: Set Conda path
      run: echo "::add-path::$CONDA/condabin"
      shell: bash

    - name: Install Conda deps
      run: |
        conda update -qy --all
        conda install -qy conda-build

    - name: Check Pickle5 status
      id: p5-status
      shell: pwsh
      run: |
        cd conda
        & ./check-pickle5.ps1

    - name: Build Pickle5 packages
      run: conda build conda/pickle5
      if: steps.p5-status.outputs.up_to_date != 'true'

    - name: Build BinPickle packages
      run: conda build -c lenskit conda/binpickle

    - name: Copy Conda packages
      run: |
        $ddir = (Join-Path dist ${{matrix.condaplat}})
        $bld = (Join-Path $env:CONDA conda-bld ${{matrix.condaplat}})
        New-Item -Type Directory $ddir
        Get-ChildItem $bld |Copy-Item -Destination $ddir
        Get-ChildItem -Recurse dist
      shell: pwsh

    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: conda-pkgs
        path: dist

  upload:
    name: Publish packages
    runs-on: ubuntu-latest
    needs: [sdist, conda]

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set Conda path
        run: echo "::add-path::$CONDA/condabin"
        shell: bash

      - name: Install Conda deps
        run: |
          conda update -qy --all
          conda install -qy anaconda-client twine

      - name: Fetch PyPI artifacts
        uses: actions/download-artifact@v2
        with:
          name: pypi-pkgs
          path: dist

      - name: Fetch Conda artifacts
        uses: actions/download-artifact@v2
        with:
          name: conda-pkgs
          path: dist

      - name: List dist dir
        run: ls -R dist

      - name: Publish PyPI packages
        if: github.event_name == 'release'
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate base
          twine upload dist/binpickle*.tar.gz dist/binpickle*.whl
        shell: bash
        env:
          TWINE_NON_INTERACTIVE: y
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

      - name: Publish Conda packages
        if: github.event_name == 'release'
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate base
          if ls dist/*/pickle5.tar.bz2; then
            anaconda upload -u lenskit --skip-existing dist/*/pickle5*.tar.bz2
          fi
          anaconda upload -u lenskit dist/*/binpickle*.tar.bz2
        shell: bash
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_TOKEN }}
